services:
  env-generator:
    image: python:3.10-slim
    container_name: env-generator
    volumes:
      - "./scripts:/scripts"
      - "./models.d:/models.d"
      - "./env:/env"
    working_dir: /scripts
    entrypoint: ["/bin/sh", "-c", "pip install --no-cache-dir json5 && python3 generate_env_local.py"]

  huggingchat-ui:
    container_name: just-chat-ui
    image: ghcr.io/longevity-genie/chat-ui/chat-ui:latest
    environment:
      ALLOW_INSECURE_COOKIES: "true"
      INCLUDE_DB: "False"
    volumes:
      - "./env/.env.local:/app/.env.local"
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      env-generator:
        condition: service_completed_successfully
    restart: "no"

  chat-mongo:
    container_name: just-chat-mongodb
    image: mongo:latest
    restart: always
    env_file:
      - .env.db
    ports:
      - "27017"
    volumes:
      - "./volumes/mongo/db:/data/db"

networks:
  default:
    name: chat-server
